# Site Settings
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "tr-TR"
title: "Serdar İlder Çağlar"
title_separator: "-"
subtitle: "AI/ML Engineering Lead & Solutions Architect"
name: "Serdar İlder Çağlar"
description: "AI/ML Engineering, RAG Systems, Production ML Solutions"
url: "https://serdarildercaglar.github.io"
baseurl: ""
repository: "serdarildercaglar/serdarildercaglar.github.io"
teaser: # path of fallback teaser image
logo: # path of logo image to display in the masthead
masthead_title: # overrides the website title displayed in the masthead
breadcrumbs: true

# Site Author
author:
  name: "Serdar İlder Çağlar"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "AI/ML Engineering Lead & Solutions Architect specializing in Production-Grade RAG Systems"
  location: "Ordu, Turkey"
  email: "serdarildercaglar@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:serdarildercaglar@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/serdarildercaglar/"
    - label: "Hugging Face"
      icon: "fas fa-fw fa-robot"
      url: "https://huggingface.co/serdarcaglar"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/serdarildercaglar"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/serdarildercaglar/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/serdarildercaglar"
    - label: "Hugging Face"
      icon: "fas fa-fw fa-robot"
      url: "https://huggingface.co/serdarcaglar"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Istanbul

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

# SEO
google_site_verification: # Google Search Console verification
bing_site_verification: # Bing Webmaster Tools verification

# Social Sharing
twitter:
  username: # Add if you have Twitter

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: # Add your Google Analytics ID

# Comments
comments:
  provider: "disqus"
  disqus:
    shortname: # Add your Disqus shortname if you want comments